--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-sync
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-sync
  template:
    metadata:
      labels:
        app: gitea-sync
    spec:
      imagePullSecrets:
        - name: gitea-registry
      containers:
        - name: gitea-sync
          image: gitea.localhost:8443/gitea-admin/gitea-sync:latest
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
          ports:
            - containerPort: 8080
