apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lab
servers: 1
agents: 2
image: rancher/k3s:v1.34.1-k3s1
kubeAPI:
  host: "127.0.0.1"
  hostPort: "6445"

ports:
  - port: 0.0.0.0:8080:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:8443:443
    nodeFilters:
      - loadbalancer

volumes:
  - volume: ${PWD}/sensitive/corp-self-signed.crt:/usr/local/share/ca-certificates/corporate.crt
    nodeFilters:
      - all

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:0
